# Generated by Django 3.2.9 on 2021-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=200, unique=True)),
                ('logo', models.FileField(default=None, upload_to='')),
                ('status', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.IntegerField(max_length=200, unique=True)),
            ],
        ),
    ]
