# Generated by Django 3.2.9 on 2021-11-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='size',
            old_name='small',
            new_name='brandsize',
        ),
    ]
