# Generated by Django 3.2.9 on 2021-11-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cloth',
            new_name='brandcategory',
        ),
    ]
