# Generated by Django 3.2.9 on 2021-11-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_cloth_category_brandcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Page',
            fields=[
                ('masterid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('document', models.FileField(default=None, upload_to='')),
                ('price', models.CharField(max_length=200)),
                ('brandcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('brandname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('brandsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.size')),
            ],
        ),
    ]
