# Generated by Django 3.2.9 on 2021-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_master_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_page',
            name='masterstatus',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
