# Generated by Django 2.2.1 on 2021-11-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_master_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_page',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
